server:
  port: 8080
spring:
  application:
    name: "appPersons"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/test"
  rabbitmq:
      host: "woodpecker-01.rmq.cloudamqp.com"
      username: "lpitulnf"
      password: "SImuVFyvYhNnRwd_KmLiDVQDffW0GvuG"
      virtual_host: "lpitulnf"
      port: 5672
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

